<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>KerbalHealth</AssemblyName>
    <RootNamespace>KerbalHealth</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyVersion>1.6.8.100</AssemblyVersion>
    <FileVersion>1.6.8.100</FileVersion>
    <InformationalVersion>1.6.9-pre</InformationalVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugType>none</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>GameData\KerbalHealth\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>GameData\KerbalHealth\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP_x64_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP_x64_Data\Managed\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="KH_CLSInterfaces, Version=2.0.0.6, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>GameData\KerbalHealth\KH_CLSInterfaces.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="UnityEngine">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP_x64_Data\Managed\UnityEngine.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP_x64_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP_x64_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP_x64_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP_x64_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\KSP_x64_Data\Managed\UnityEngine.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="GameData\KerbalHealth\icon.png" />
    <None Include="GameData\KerbalHealth\Localization\en-us.cfg" />
    <None Include="GameData\KerbalHealth\Localization\zh-cn.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHRationalResources.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHDMOS.cfg" />
    <Content Include="GameData\KerbalHealth\KH_CLSInterfaces.dll" />
    <Content Include="GameData\KerbalHealth\toolbar.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="GameData\KerbalHealth\KerbalHealth.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHEPL.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHFelineUtilityRover.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHFTT.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHJNSQ.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHKaribou.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHNearFutureExploration.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHNFA.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHNFE.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHMalemute.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHNearFutureSpacecraft.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHOPM.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHReStockPlus.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHSEP.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHSSPX.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHTantares.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHTokamak.cfg" />
    <None Include="GameData\KerbalHealth\KerbalHealth.version" />
    <None Include="GameData\KerbalHealth\LICENSE" />
    <None Include="GameData\KerbalHealth\Patches\General.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHAtomicAge.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHBDB.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHDeepFreeze.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHDSEV.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHFASA.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHB9.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHDeadlyReentry.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHFTmN.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHFTmN_New.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHIE.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHKerbalAtomics.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHKPBS.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHMakingHistory.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHMKS.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHRLA.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHRSCapsuledyne.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHSpaceY.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHSSTU.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHStock.cfg" />
    <None Include="GameData\KerbalHealth\Patches\KHUSILS.cfg" />
    <None Include="README.md" />
    <None Include="GameData\KerbalHealth\Resources.cfg" />
  </ItemGroup>
</Project>
